In [2]:
import numpy as np

In [ ]:
##Q1- Create an array of integers between -10 and 10

In [31]:
a = np.array(range(-11, 10)) +1 #Solution of Q1
print(type(a), a)

<class 'numpy.ndarray'> [-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9  10]


In [ ]:
## Q2- (a)Extract every other value from array D starting from the 2nd value through the 10th value. Store the result in a variable called x.

In [133]:
D = np.array(range(18)) + 3    #Solution of (a)
print(D)
x = D[2:10]
print(x)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 5  6  7  8  9 10 11 12]


In [ ]:
## (b)Extract every other value from array D starting from the 10th value through the 2nd value. Store the result in a variable called y.

In [148]:
z = D[::-1] # (c) Create a variable z that contains all of the values in D in reverse order.
print(z)
y = z[8:-2] # solution of (b)
print(y)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3]
[12 11 10  9  8  7  6  5]


In [ ]:
(c) Create a variable z that contains all of the values in D in reverse order.

In [119]:
a = np.random.randint(10,50, (5,5))
a

array([[30, 38, 15, 42, 27],
       [28, 45, 25, 41, 31],
       [31, 46, 17, 17, 38],
       [21, 11, 15, 41, 32],
       [19, 17, 22, 34, 42]])

In [120]:
## Indexing
a[(2,3), 2:] ##row and column index([(2nd row, 3rd row), all from 2 column

array([[17, 17, 38],
       [15, 41, 32]])

In [151]:
Q3 = f"How are NumPy Arrays better than Lists in Python?"

In [ ]:
Ans3 = f"""NumPy is better in advanced mathematical and other types of operations on large numbers of data.
In which we can create N-Dimensonal array in python using NumPy Array. It is convenient to use and uses less data"""

In [ ]:
Q4 = f"Explain the data types supported by Numpy"

In [ ]:
Ans4 = f"""NumPy supports vast number of data types than python does.
numpy.bool_ - bool
numpy.byte - signed char
numpy.ubyte - unsigned char
numpy.short - short
numpy.ushort - unsigned short
numpy.intc - int
numpy.uintc - unsigned int
numpy.int_ - long
numpy.uint - unsigned long
numpy.longlong - long long
numpy.ulonglong - unsigned long long
numpy.half / numpy.float16
numpy.single - float
numpy.double - double
numpy.longdouble - long double
numpy.csingle - float complex
numpy.cdouble - double complex
numpy.clongdouble - long double complex"""